# Generated by Django 4.1.7 on 2023-03-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(db_index=True, max_length=128)),
                ('patrinimic', models.CharField(max_length=128)),
                ('foto', models.ImageField(upload_to='./foto')),
                ('position', models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Менеджер'), ('head_of_department', 'Руководитель отдела')], max_length=18)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.PositiveSmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='staff.department')),
            ],
        ),
    ]
